# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da182c55e747ac1bac89cafd025d2283063974024ce7eb77c0bb91c73944519dd9d517637a3186adaf8cce92303ca7e24b34637905bf3225ab45a6a0c7db65dc

test:
  secret_key_base: 9f21f488d41ee2aa55347a382440a2222526f28fda7f9b95bc61632230829a1f54f90fd15912e560eb48027c3cff161233ec9a9d9e67447a2cf607569dc8f645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
